-- CREATE DATABASE GameDB;

CREATE TABLE accounts(
	accountID INTEGER NOT NULL,
	accountName VARCHAR(10) NOT NULL,
	coins INTEGER DEFAULT 0,
	createTime DATETIME
);

SELECT *
FROM accounts;

DROP TABLE accounts

ALTER TABLE accounts
ADD lastEnterTime DATETIME;

ALTER TABLE accounts
DROP COLUMN lastEnterTime;

ALTER TABLE accounts
ALTER COLUMN accountName VARCHAR(20) NOT NULL;

ALTER TABLE accounts
ADD CONSTRAINT TT PRIMARY KEY (accountID)

ALTER TABLE accounts
DROP CONSTRAINT TT